-- Wick's Survivors
-- Anim.lua: flipbook animation for sprite strip textures
--
-- Frame data (frames + per-frame UV fraction) is generated by the PNG->TGA
-- converter (sprites-to-tga.py -> anim_manifest.json) and pasted in below.
-- The `frac` is the U width of one frame within the texture. For most strips
-- frac == 1/frames, but padded non-power-of-two strips (proj_dreadhound,
-- proj_wolf were 768px wide, padded to 1024) have frac < 1/frames, so the
-- empty padding columns are never sampled. fps is curated per sprite for feel.

local ADDON, ns = ...
local WS = WicksSurvivors

-- Default playback rate; overridden per-key in FPS below.
local DEFAULT_FPS = 9

local FPS = {
    player       = 6,
    -- base enemies
    ghoul = 10, wraith = 8, abomination = 7, banshee = 9, lich = 7,
    frostling = 11, frost_revenant = 8, magma_hound = 9, cinder_wisp = 12,
    deep_spawn = 8, gazer = 7, fel_imp = 11, wrathguard = 7,
    -- bosses
    boss_kel = 6, boss_nef = 6, boss_cthun = 8, boss_illidan = 7,
    boss_kel_empowered = 8, boss_nef_empowered = 8,
    boss_cthun_empowered = 10, boss_illidan_empowered = 9,
    -- projectiles / weapon entities
    proj_orb = 14, proj_aura = 12, proj_meteor = 14,
    proj_dreadhound = 11, proj_wolf = 11,
    -- biome props (slow ambient flicker)
    el_eye = 6, el_pod = 5, el_tentacle = 6, em_vent = 8,
    fl_brazier = 10, fl_circle = 5, fc_brazier = 10,
}

-- frames + frac per animated key (from anim_manifest.json). Static sprites are
-- omitted; SetAnimFrame is a no-op for those keys.
WS.ANIM = {
    player = {frames=4, frac=0.25},

    ghoul          = {frames=8, frac=0.125},
    wraith         = {frames=8, frac=0.125},
    abomination    = {frames=8, frac=0.125},
    banshee        = {frames=8, frac=0.125},
    lich           = {frames=8, frac=0.125},
    frostling      = {frames=8, frac=0.125},
    frost_revenant = {frames=8, frac=0.125},
    magma_hound    = {frames=8, frac=0.125},
    cinder_wisp    = {frames=8, frac=0.125},
    deep_spawn     = {frames=8, frac=0.125},
    gazer          = {frames=8, frac=0.125},
    fel_imp        = {frames=8, frac=0.125},
    wrathguard     = {frames=8, frac=0.125},

    -- reskins
    ghoul_frost = {frames=8, frac=0.125}, ghoul_ember = {frames=8, frac=0.125},
    ghoul_eldritch = {frames=8, frac=0.125}, ghoul_fel = {frames=8, frac=0.125},
    wraith_frost = {frames=8, frac=0.125}, wraith_ember = {frames=8, frac=0.125},
    wraith_eldritch = {frames=8, frac=0.125}, wraith_fel = {frames=8, frac=0.125},
    abomination_frost = {frames=8, frac=0.125}, abomination_ember = {frames=8, frac=0.125},
    abomination_eldritch = {frames=8, frac=0.125}, abomination_fel = {frames=8, frac=0.125},
    banshee_frost = {frames=8, frac=0.125}, banshee_ember = {frames=8, frac=0.125},
    banshee_eldritch = {frames=8, frac=0.125}, banshee_fel = {frames=8, frac=0.125},
    lich_frost = {frames=8, frac=0.125}, lich_ember = {frames=8, frac=0.125},
    lich_eldritch = {frames=8, frac=0.125}, lich_fel = {frames=8, frac=0.125},

    -- bosses
    boss_kel = {frames=4, frac=0.25}, boss_nef = {frames=4, frac=0.25},
    boss_cthun = {frames=4, frac=0.25}, boss_illidan = {frames=4, frac=0.25},
    boss_kel_empowered = {frames=4, frac=0.25}, boss_nef_empowered = {frames=4, frac=0.25},
    boss_cthun_empowered = {frames=4, frac=0.25}, boss_illidan_empowered = {frames=4, frac=0.25},

    -- animated projectiles / weapon entities
    proj_orb      = {frames=8, frac=0.125},
    proj_aura     = {frames=8, frac=0.125},
    proj_meteor   = {frames=8, frac=0.125},
    proj_dreadhound = {frames=6, frac=0.125}, -- padded 768->1024, 6 real frames
    proj_wolf       = {frames=6, frac=0.125}, -- padded 768->1024, 6 real frames

    -- animated biome props (8-frame flicker strips, 2048x256)
    el_eye      = {frames=8, frac=0.125},
    el_pod      = {frames=8, frac=0.125},
    el_tentacle = {frames=8, frac=0.125},
    em_vent     = {frames=8, frac=0.125},
    fl_brazier  = {frames=8, frac=0.125},
    fl_circle   = {frames=8, frac=0.125},
    fc_brazier  = {frames=8, frac=0.125},
}

-- Set the UV coords on texObj to show the correct animation frame.
-- key   : matches a WS.ANIM entry (e.g. "ghoul", "player", "ghoul_frost")
-- phase : 0-1 offset so pooled frames don't all sync together
function WS.SetAnimFrame(texObj, key, phase)
    local a = WS.ANIM[key]
    if not a then
        texObj:SetTexCoord(0, 1, 0, 1)
        return
    end
    local n   = a.frames
    local fps = FPS[key] or DEFAULT_FPS
    local idx = math.floor(GetTime() * fps + (phase or 0) * n) % n
    local l   = idx * a.frac
    texObj:SetTexCoord(l, l + a.frac, 0, 1)
end
